version: '3.4'

services:
  app:
    image: 'antoniosk/desafio-api:latest'
    container_name: desafio
    depends_on:
      - db
    links:
      - db
    environment:
      - MAIL_PROFILE_SENDER=sendgrid
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=desafio-api
      - SENDGRID_API_KEY=api_key
      - SENDGRID_FROM_EMAIL=from_email
      - SENDGRID_FROM_NAME=from_name
      - MAIL_HOST=smtp-mail.outlook.com
      - MAIL_PORT=587
      - MAIL_PROTOCOL=smtp
      - MAIL_USERNAME=username
      - MAIL_PASSWORD=password
      - TOKEN_ISSUER=issuer
      - JWT_ACCESS_SECRET=my_access_secret
      - JWT_ACCESS_EXPIRATION_TIME=1800000
      - JWT_REFRESH_SECRET=my_refresh_secret
      - JWT_REFRESH_EXPIRATION_TIME=86400000
      - URL_CORS=http://localhost:8080
  db:
    image: 'mysql:8.0.31'
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=desafio-api
