spring:
  datasource:
    url: jdbc:mysql://localhost:3306/desafio_api?createDatabaseIfNotExist=True&jdbcCompliantTruncation=false
    username: root
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    protocol: smtp
    host: smtp-mail.outlook.com
    port: 587
    username: username@mail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  profiles:
    active: @active.profile@

springdoc:
  api-docs:
    path: /swagger

security:
  url-cors: http://localhost:8080 http://localhost:8081
  token:
    issuer: antonio

    access_secret: my_access_secret
    access_expiration: 1800000

    refresh_secret: my_refresh_secret
    refresh_expiration: 86400000

generate:
  admin:
    email: email1@hotmail.com
    password: senha123

  user:
    email: email2@gmail.com
    password: senha123