spring:
  datasource:
    url: jdbc:mysql://localhost:3306/desafio_api?createDatabaseIfNotExist=True&jdbcCompliantTruncation=false
    username: root
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mail:
    protocol: smtp
    host: smtp-mail.outlook.com
    port: 587
    username: antonio.sgarbi@hotmail.com
    password: thym3l34f@flux
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

springdoc:
  api-docs:
    path: /swagger

security:
  url-cors: http://localhost:8080 http://localhost:8081
  token:
    issuer: antonio

    access_secret: my_access_secret
    access_expiration: 1800000

    refresh_secret: my_refresh_secret
    refresh_expiration: 86400000
